plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.11'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
    id 'idea'
}

group = 'com.evi.login.processor'
version = '0.0.1-SNAPSHOT'
description = 'Evi login processor'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }

    integrationTestImplementation.extendsFrom testImplementation
    integrationTestRuntimeOnly.extendsFrom testRuntimeOnly
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring WebFlux & Reactive
    implementation 'org.springframework.boot:spring-boot-starter-webflux'

    // Kafka
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'io.projectreactor.kafka:reactor-kafka'
//    implementation 'org.apache.kafka:kafka-streams' //enables processing streams support

    // JPA + DB
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // Spring Data R2DBC (Reactive database access)
    implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'

    // R2DBC PostgreSQL driver
    implementation 'org.postgresql:r2dbc-postgresql'

    // JSON support
    implementation 'org.springframework.boot:spring-boot-starter-json'

    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Testing
    testImplementation 'io.projectreactor:reactor-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:kafka'
    testImplementation 'org.testcontainers:postgresql'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.mockito:mockito-core:5.7.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.17.0'

    integrationTestImplementation 'org.testcontainers:junit-jupiter'
    integrationTestImplementation 'org.wiremock.integrations:wiremock-spring-boot:4.2.1'


    // Integration test dependencies
    integrationTestImplementation sourceSets.test.output
}

springBoot {
    mainClass = 'com.evi.login.processor.EviLoginTrackerApplication'
    buildInfo()
}

tasks.named('bootJar') {
    archiveFileName = "${project.name}-${project.version}.jar"
}

tasks.withType(Test) {
    useJUnitPlatform()
}

test {
    useJUnitPlatform()
}

sourceSets {
    integrationTest {
        java.srcDir file("src/integrationTest/java")
        resources.srcDir file("src/integrationTest/resources")
        runtimeClasspath += sourceSets.main.runtimeClasspath + sourceSets.test.runtimeClasspath
        compileClasspath += sourceSets.main.compileClasspath + sourceSets.test.compileClasspath
    }
}


// code coverage
jacoco {
    toolVersion = "0.8.14"
}

jacocoTestCoverageVerification {
    violationRules {
        rule {
            limit {
                minimum = 0.90
            }
        }
    }
}

jacocoTestReport {
    dependsOn test
}
jacocoTestCoverageVerification {
    dependsOn test
}

tasks.register('integrationTest', Test) {
    description = 'Runs integration tests'
    group = 'verification'

    testClassesDirs = sourceSets.integrationTest.output.classesDirs
    classpath = sourceSets.integrationTest.runtimeClasspath

    useJUnitPlatform()
}

idea {
    module {
        sourceSets.integrationTest.allSource.srcDirs.each { srcDir -> module.testSourceDirs += srcDir }
    }
}